[package]
name = "chimera-kube-policy-sdk"
version = "0.1.0"
authors = ["Flavio Castelli <fcastelli@suse.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
k8s-openapi = { version = "0.11.0", default-features = true, features = ["v1_20"] }
jmespatch = "0.3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
wapc-guest = "0.4.0"
