name: Release
on:
  push:
    tags:
    - 'v*'
env:
  CARGO_TERM_COLOR: always
jobs:

  ci:
    # A branch is required, and cannot be dynamic - https://github.com/actions/runner/issues/1493
    uses: kubewarden/policy-sdk-rust/.github/workflows/tests.yml@main

  release:
    name: Create release
    runs-on: ubuntu-latest
    needs:
      - ci
    steps:
    - name: Create Release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Kubewarden Rust SDK ${{ github.ref }}
        draft: false
        prerelease: ${{ contains(github.ref, '-alpha') || contains(github.ref, '-beta') || contains(github.ref, '-rc') }}

  publish:
    name: Publish on crates.io
    runs-on: ubuntu-latest
    needs:
      - ci
    steps:
      -  uses: actions/checkout@v3
      -  uses: actions-rs/toolchain@v1
         with:
           toolchain: stable
           override: true

      - name: publish crates
        run: cargo publish --token ${{ secrets.CARGO_API_TOKEN }}
